name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore ./src/ScopedHostedService.sln


      - name: Build
        run: dotnet build ./src/ScopedHostedService.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./src/ScopedHostedService.sln --configuration Release --no-restore

